# Generated by Django 2.1.7 on 2019-02-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_mail',
        ),
        migrations.RemoveField(
            model_name='message',
            name='author_name',
        ),
    ]
